### ISSUE TITLE
IRP unload

### ISSUE THREAD

**Issue by fwf02** [AngleHony/WKTools#11]
is it possible add a IRP unload for drivers ?

To unload an IRP, the driver typically needs to complete the processing of the IRP and release any resources that were allocated for it. This is typically done by calling the IoCompleteRequest function, which signals the operating system that the IRP has been completed and can be freed.

**Comment by AngleHony** [comment]
Oh Y can  use Unload Driver Function ----It will call the Target Driver unload function( == Send UNLOAD IRP)

**Comment by fwf02** [comment]
thank you im talking about this one 
![sdc](https://user-images.githubusercontent.com/27238585/233776880-3e6de9f1-2a3d-412f-81ab-2184ecb03018.jpg)

**Comment by AngleHony** [comment]
OK I get it, The next version  will show IRP unload  address.   Before 5.5

**Comment by fwf02** [comment]
hey there still no unload IRP in new version  
![index](https://github.com/AngleHony/WKTools/assets/27238585/cf4e4dac-19d5-4e15-ae00-7e1d31e115cf)

**Comment by AngleHony** [comment]
![Snipaste_2023-05-12_22-48-59](https://github.com/AngleHony/WKTools/assets/15376696/56063558-427a-4150-88c4-8ecae9e8b465)

**Comment by fwf02** [comment]
yes but i was wondering if its possible to  add unload routine in refresh view all only show danger properties find target in explroer export to to text

**Comment by AngleHony** [comment]
#12
