### ISSUE TITLE
Add Unload on IRP 

### ISSUE THREAD

**Issue by xmanx1996** [AngleHony/WKTools#12]
Possible to add unload button here?

![image](https://github.com/AngleHony/WKTools/assets/133463695/ac526fa7-b843-4ce2-9a3d-8aa016e78b20)

**Comment by fwf02** [comment]
yes thats what im looking for as well !

**Comment by AngleHony** [comment]
Just Only remove the target Irp(set the target IRP Entry = 0) ?

**Comment by fwf02** [comment]
a button that we can unload every IRP in driver routine like the image  if its possible!

**Comment by AngleHony** [comment]
unload every IRP == Disable every IRP ?   

when  Use This function ?  such as.......

**Comment by fwf02** [comment]
yes

**Comment by AngleHony** [comment]
> yes

when Use This function ? such as.......

**Comment by fwf02** [comment]
> > yes
> 
> when Use This function ? such as.......



 such as IoMarkIrpPending(). This will tell the I/O Manager that the driver is not yet done with the IRP, and the I/O Manager will not complete the IRP until the driver indicates that it's finished make button of this function 

suspend IRP Freeze IRP or unload(if its possible)

**Comment by AngleHony** [comment]
I dont think this case is  High frequency scene.

**Comment by fwf02** [comment]
> I dont think this case is High frequency scene.

i see thank you  !
