### ISSUE TITLE
Request Injection 

### ISSUE THREAD

**Issue by xmanx1996** [AngleHony/WKTools#15]
![image](https://github.com/AngleHony/WKTools/assets/133463695/29a5b241-8c9f-44d6-a2bf-b6b39467b6a7)

Can you add like this?

**Comment by AngleHony** [comment]
I get It, Next Ver Wiil support.

**Comment by xmanx1996** [comment]
Thank you very much,i'll be wait for the new update <3

**Comment by xmanx1996** [comment]
@AngleHony  By the way , did you include IRP unload button next version?
