### ISSUE TITLE
解除窗口保护失败

### ISSUE THREAD

**Issue by KomeijiReimu** [AngleHony/WKTools#20]
解除显示为monitor的保护窗口后，刷新仍然显示保护，实际上保护解除失败。
同时启动时会释放多个驱动文件
![image](https://github.com/AngleHony/WKTools/assets/118449321/42345f0c-5219-4781-ae81-fba54996353d)

系统版本：
`win11 22h2 22621.1848`

**Comment by KomeijiReimu** [comment]
wait  wait wait

**Comment by AngleHony** [comment]
1  释放多个驱动文件为已知BUG。
2   关于保护窗口解除失败,可以提供样本,或者远程环境,方便我定位解决

**Comment by KomeijiReimu** [comment]
> 1 释放多个驱动文件为已知BUG。 2 关于保护窗口解除失败,可以提供样本,或者远程环境,方便我定位解决

请到这里下载样本：

**Comment by AngleHony** [comment]
![Snipaste_2023-10-27_10-25-35](https://github.com/AngleHony/WKTools/assets/15376696/f94b09fb-5254-462f-b9a8-8aca88afcbc1)

**Comment by KomeijiReimu** [comment]
👍🏻
