### ISSUE TITLE
shadow ssdt排序似乎不正确

### ISSUE THREAD

**Issue by ddkwork** [AngleHony/WKTools#21]
![1699795998561.png](https://github.com/AngleHony/WKTools/assets/19886504/72db27fd-6572-49a2-850d-7a54e6de8298)

**Comment by AngleHony** [comment]
系统版本号提供下

**Comment by ddkwork** [comment]
> 系统版本号提供下

22000

**Comment by AngleHony** [comment]
https://github.com/AxtMueller/Windows-Kernel-Explorer  用这个软件试试, 看看结果

**Comment by ddkwork** [comment]
> https://github.com/AxtMueller/Windows-Kernel-Explorer  用这个软件试试, 看看结果

这个之前试了不行，不过我试了另外一个还是看到和您的不一样，bug是最后一个api的index，shadow反汇编是4096开始的，减去4096从0排序看到最后一个api不是那个doc名字的api，我这边写了个工具获取对比过了。

**Comment by ddkwork** [comment]
从win32u.dll和win32k.sys解析pe获取都能验证这个shadow bug的

**Comment by AngleHony** [comment]
问题已确认,谢谢

**Comment by AngleHony** [comment]
> > 系统版本号提供下
> 
> Win11 22000

把大版本号小版本号都提供下

**Comment by ddkwork** [comment]
> > > 系统版本号提供下
> > 
> > 
> > Win11 22000版本
> 
> 把大版本号小版本号都提供下
[ntdll.txt](https://github.com/AngleHony/WKTools/files/13439162/ntdll.txt)
[win32u.txt](https://github.com/AngleHony/WKTools/files/13439163/win32u.txt)

**Comment by ddkwork** [comment]
文件第一行我写入版本号了

**Comment by AngleHony** [comment]
微软小版本更新导致的,我没有适配，问题已经定位到了

**Comment by ddkwork** [comment]
> 微软小版本更新导致的,我没有适配，问题已经定位到了

用反汇编引擎取eax无论怎么更新都能娶到正确的number吧
