### ISSUE TITLE
不支持的操作系统

### ISSUE THREAD

**Issue by FlycanA** [AngleHony/WKTools#22]
操作系统不支持：
![微信图片_20231115230736](https://github.com/AngleHony/WKTools/assets/89075536/5ffbc782-0cd8-4718-a1cb-4ad72861406e)
![微信截图_20231115230815](https://github.com/AngleHony/WKTools/assets/89075536/a0fd6940-9a3d-4a6b-84ae-6d29be5cb592)

**Comment by AngleHony** [comment]
版本太旧, 不打算支持,可以用PCHUNTER
