### ISSUE TITLE
Not work in Windows 11 23H2 22631

### ISSUE THREAD

**Issue by Gonzalok91** [AngleHony/WKTools#25]
Hello, in the new Windows 11 update the program does not work, I am waiting for an update. Thanks for your job.

**Comment by AngleHony** [comment]
Next version  Before12.31

**Comment by Gonzalok91** [comment]
> Next version Before12.31

Thanks!!

**Comment by githubsearcher11** [comment]
any updates? :(

**Comment by AngleHony** [comment]
Sorry, Too late, 1.0.0.17 Now support

**Comment by githubsearcher11** [comment]
Thank you as always!
