### ISSUE TITLE
certificate

### ISSUE THREAD

**Issue by MisterBr306** [AngleHony/WKTools#29]
---------------------------
WKTools
---------------------------
Failed to load the diver. ErrorCode 0x800b010c Certificado explicitamente revogado por seu emissor.

---------------------------
OK   
---------------------------

**Comment by FlycanA** [comment]
Me too!I  also meet this issue.

**Comment by qc2t** [comment]
Me too!

**Comment by AngleHony** [comment]
I have update, Fix this error, tks

**Comment by Johnschiffer** [comment]
Thank you very much!
Your app is the best in its category.
