### ISSUE TITLE
启动程序时加载驱动失败

### ISSUE THREAD

**Issue by ruoxu233** [AngleHony/WKTools#4]
![image](https://user-images.githubusercontent.com/62586173/187656369-a302006e-c0e1-4ee2-bada-619dcec80c57.png)

Windows 规格：
    版本：Windows 10 专业版
    版本号：1809
    操作系统版本：17763.737
Windows 开启了测试模式

**Comment by AngleHony** [comment]
System Support Win7X64 (7601) Win10X64 (19041,19042,19043,19044) Win11(22000)

**Comment by elf-world** [comment]
版本	Windows 11 企业版
版本	21H2
安装日期	‎2022/‎9/‎19
操作系统版本	22000.978
驱动打开失败

**Comment by AngleHony** [comment]
1 关闭HVCI
2 关闭杀毒软件

**Comment by AngleHony** [comment]
> 版本 Windows 11 企业版 版本 21H2 安装日期 ‎2022/‎9/‎19 操作系统版本 22000.978 驱动打开失败

1 关闭HVCI
2 关闭杀毒软件
