### ISSUE TITLE
Request 

### ISSUE THREAD

**Issue by ralphungria** [AngleHony/WKTools#5]
Request deleting Callback notificaion thank you <3

Like WKE64 have call back nitification deletion thanks ^_^

**Comment by AngleHony** [comment]
This Is Now Support Callback--> RightClick--> Remove

**Comment by ralphungria** [comment]
I cant see Angel...Any way, possible to delete this Object Type ? 

https://imgur.com/dqjD4gV

https://imgur.com/vjoRdzH

**Comment by AngleHony** [comment]
![CallBack](https://user-images.githubusercontent.com/15376696/192235448-50e8e3f9-10d1-417e-aaaf-4764d8fddb58.png)

**Comment by ralphungria** [comment]
ahhhh okay2x thank you Angel <3...ahmm Is there any update soon ^_^.

**Comment by ralphungria** [comment]
Do you know ClownQq/YDArk Tool wont open on my PC ? 

Edition	        Windows 10 Pro N
Version	        21H2
Installed on	‎9/‎24/‎2022
OS build	        19044.1288
Experience	Windows Feature Experience Pack 120.2212.3920.0

**Comment by ralphungria** [comment]
Its works now sorry <3
