### ISSUE TITLE
Added Ending the alibabaprotect.exe process

### ISSUE THREAD

**Issue by eremiter** [AngleHony/WKTools#7]
win11,Using the wktools tool, alibabaprotect process cannot be found in the window, but an alibaba process and a handle are found in the resource monitor, which can be safely removed to protect the removable hard drive.

**Comment by AngleHony** [comment]
![Snipaste_2022-11-03_14-51-41](https://user-images.githubusercontent.com/15376696/199662084-2072fccc-6789-4815-bab2-9ebdb7a6f712.png)
I test In My Pc, EveryThing Is OK, I hope you can provide More infomation  operate step。

**Comment by eremiter** [comment]
Hello Sir,

Thanks,I see,

Best regards,
 
From: AngleHony
Date: 2022-11-03 15:02
To: AngleHony/WKTools
CC: erepig; Author
Subject: Re: [AngleHony/WKTools] Added Ending the alibabaprotect.exe process (Issue #7)

I test In My Pc, EveryThing Is OK, I hope you can provide More infomation operate step。
